
# hyprland 生态
# exec-once = hyprpm reload -n s  # hyprland插件
exec-once=hyprpaper &             # 壁纸
exec-once=hypridle &              # 电源守护进程

# fcitx
exec-once=fcitx5 -d &

# network
exec-once = nm-applet &

# status bar
exec-once=waybar &

# dunst
exec-once=dunst &

# gui auth
exec-once=/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &


#start your app

# exec-once = [workspace 1 silent] google-chrome
# exec-once = [workspace 2 silent] alacritty
