windowrulev2 = float, class:^(dunst)$
# # xfce-polkit
# windowrulev2 = float, class:xfce-polkit
# windowrulev2 = fullscreen, class:alacritty, title:.*BpyTOP.*

# # opacity
# windowrulev2 = opacity 0.5, class:code
# windowrulev2 = opacity 0.92, class:Google-chrome
